const hoststab=[
    {
        _id: 2020,
        title: "Arabic coffee",
        host: "Asma FAKHFAKH",
        activity: "Drink",
        destination: "Sousse",
        price: 4,
        rating: 3,
        description: "Join the family on a cup of arabic coffee with home-made traditional sweets. We will be chatting about life and cats",
        imgsrc:'https://static.boredpanda.com/blog/wp-content/uploads/2017/01/two-faced-cat-yana-28.jpg',
    },
    {
        _id: 3030,
        title: "Lablebi",
        host: "Houssem Trabelsi",
        activity: "Food",
        destination: "Sousse",
        price: 3,
        rating: 1,
        description: "Lablebi is a famous tunisian food made with chickpeas. Warning: be ready to spice it up",
        imgsrc:'https://steemitimages.com/DQmRpnB8guFd4VkcZgLhtFMbjxqDQeqxzb5r4cYREin64CH/18645915_148001462408917_5174778861115670528_n.jpg',
    },
    {
        _id: 4040,
        title: "Spéléologie",
        host: "Rabii Ben Brahim",
        activity: "Sport",
        destination: "Siliana",
        price: 10,
        rating: 2,
        description: "Come and discover the amazing cave of Ain Dhab. Necessary equipment is provided",
        imgsrc:'https://www.intrepides-jura.com/1409-large_default/initiation-speleo-aquatique.jpg',
    },
    {
        _id: 5050,
        title: "Brunch traditionnel",
        host: "Houssem Trabelsi",
        activity: "Brunch",
        destination: "Sousse",
        price: 3,
        rating: 3,
        description: "Lablebi is a famous tunisian food made with chickpeas. Warning: be ready to spice it up",
        imgsrc:'https://steemitimages.com/DQmRpnB8guFd4VkcZgLhtFMbjxqDQeqxzb5r4cYREin64CH/18645915_148001462408917_5174778861115670528_n.jpg',
    },
    {
        _id: 6060,
        title: "Medina de Tunis",
        host: "Asma Fakhfakh",
        activity: "Guided tour",
        destination: "Tunis",
        price: 10,
        rating: 5,
        description: "Discover the unknown magic of the Medina of Tunis, and get lost in its beauty",
        imgsrc:'http://tgv.com.tn/tgv/wp-content/uploads/2016/10/guided_tour_tunis_20161-TGV-Medina.jpg',
    },
    {
        _id: 7070,
        title: "Arabic coffee",
        host: "Asma FAKHFAKH",
        activity: "Drink",
        destination: "Sousse",
        price: 4,
        rating: 1,
        description: "Join the family on a cup of arabic coffee with home-made traditional sweets. We will be chatting about life and cats",
        imgsrc:'https://static.boredpanda.com/blog/wp-content/uploads/2017/01/two-faced-cat-yana-28.jpg',
    }
]
export default hoststab;